_target_: pytorch_lightning.trainer.Trainer

default_root_dir: ${paths.output_dir}
min_epochs: Null # prevents early stopping
max_epochs: ${params.num_epochs}
accelerator: auto
devices: 1
log_every_n_steps: 1
# fast_dev_run: True
# detect_anomaly: false

# fp16 mixed precision is not supported on CPU; use "bf16-mixed" (or "16-mixed") on a GPU for a speed-up
precision: 32-true

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: false