_target_: src.models.summarization.BART.initialize

params:
  name: "facebook/bart-large-cnn"
  task: "summarization"
  max_input_length: 512
  logging_frequency: 10
  logging: true

trainer:
  params:
    batch_size: 16
    learning_rate: 3e-5
    max_epochs: 5
    lr_step_size: 10
    lr_gamma: 0.1

cache_dir: ./tmp

metric:
  _target_: torch.nn.CrossEntropyLoss
