_wandb:
    value:
        cli_version: 0.19.0
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 103
            "2":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.12.7
            "5": 0.19.0
            "6": 4.46.2
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
decoder:
    value: null
encoder:
    value: null
learning_rate:
    value: 3e-05
max_output_length:
    value: 512
tokenizer:
    value: null
