defaults:
  - task: rephrase_translate  # choose from summarization, translation, or rephrase_translate

trainer:
  max_epochs: 5
  gpus: 1  

logging:
  logging_frequency: 10

params:
  batch_size: 16
  learning_rate: 3e-5
  max_output_length: 150
  num_beams: 4
  cache_dir: "./cache"

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./multirun
  job_logging:
    root:
      handlers: [console]
  output_subdir: null
  verbose: true  # Enables detailed logging for Hydra itself
