rephrase_model_name: "facebook/bart-large-cnn"  # Choice for rephrasing
translate_model_name: "t5-small"  # Choice for translation

trainer:
  lr: 3e-5
  lr_step_size: 10
  lr_gamma: 0.1

params:
  logging_frequency: 10
  max_output_length: 150
  num_beams: 4
