# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: europarl
  - model: Null
  - logger: csv
  - callbacks: default
  - trainer: default
  - paths: default
  - hydra: default

# name determines output directory path
name: ""
# task_name determines log directory path
task_name: ""

# set False to skip model training
train: true

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: true

# provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 42

params:
  batch_size: 1
  learning_rate: 0.001
  num_epochs: 1

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.1
  patience: 5

run:
  dir: ${paths.log_dir}/${task_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}