model_name: "t5-small"  # Choose from "t5-small", "xlm-roberta-large"
task_type: "translation"

trainer:
  lr: 3e-5
  lr_step_size: 10
  lr_gamma: 0.1

params:
  logging_frequency: 10
  max_output_length: 150
  num_beams: 4
